class DomainException(Exception): ...


class InvalidUpdatedAtException(DomainException): ...


class InvalidCreatedAtException(DomainException): ...


class UserAlreadyInactiveException(DomainException): ...


class UserInactiveException(DomainException): ...


class InvalidEmailException(DomainException): ...


class InvalidPasswordException(DomainException): ...


class InvalidTokenException(DomainException): ...


class EmailAlreadyExistsException(DomainException): ...


class InvalidCredentialsException(DomainException): ...


class DocumentNotFoundException(DomainException): ...


class DocumentAccessDeniedException(DomainException): ...
