class DomainException(Exception): ...


class ValidationException(DomainException): ...


class ResourceNotFoundException(DomainException): ...


class ApplicationStateException(DomainException): ...


class InvalidUpdatedAtException(DomainException): ...


class InvalidCreatedAtException(DomainException): ...


class UserAlreadyInactiveException(DomainException): ...


class UserInactiveException(DomainException): ...


class InvalidEmailException(DomainException): ...


class InvalidPasswordException(DomainException): ...


class InvalidTokenException(DomainException): ...


class EmailAlreadyExistsException(DomainException): ...


class InvalidCredentialsException(DomainException): ...


class OAuthAuthenticationException(DomainException):
    def __init__(self, code: str, message: str | None = None) -> None:
        super().__init__(message or code)
        self.code = code


class DocumentNotFoundException(ResourceNotFoundException): ...


class DocumentAccessDeniedException(DomainException): ...


class DocumentValidationException(ValidationException): ...


class QueryValidationException(ValidationException): ...


class QueryProcessingException(ApplicationStateException): ...


class ChatNotFoundException(ResourceNotFoundException): ...
