class DomainException(Exception): ...


class ValidationException(DomainException): ...


class ResourceNotFoundException(DomainException): ...


class ApplicationStateException(DomainException): ...


class InvalidUpdatedAtException(DomainException): ...


class InvalidCreatedAtException(DomainException): ...


class UserAlreadyInactiveException(DomainException): ...


class UserInactiveException(DomainException): ...


class InvalidEmailException(DomainException): ...


class InvalidPasswordException(DomainException): ...


class InvalidTokenException(DomainException): ...


class EmailAlreadyExistsException(DomainException): ...


class InvalidCredentialsException(DomainException): ...


class DocumentNotFoundException(ResourceNotFoundException): ...


class DocumentAccessDeniedException(DomainException): ...


class DocumentValidationException(ValidationException): ...


class QueryValidationException(ValidationException): ...


class QueryProcessingException(ApplicationStateException): ...


class ChatNotFoundException(ResourceNotFoundException): ...
