from dishka import make_async_container

from src.core.providers import (
    AIProvider,
    AuthProvider,
    CacheProvider,
    CollectionSharesProvider,
    CompareProvider,
    ConflictsProvider,
    DatabaseProvider,
    DocumentsProvider,
    DraftsProvider,
    IngestionProvider,
    IntegrationsProvider,
    KnowledgeGapsProvider,
    KnowledgeGraphProvider,
    LearningGoalsProvider,
    QueryProvider,
    RepoSyncsProvider,
    StatsProvider,
    TopicsProvider,
)

container = make_async_container(
    DatabaseProvider(),
    CacheProvider(),
    AuthProvider(),
    CompareProvider(),
    ConflictsProvider(),
    CollectionSharesProvider(),
    IngestionProvider(),
    IntegrationsProvider(),
    AIProvider(),
    DocumentsProvider(),
    QueryProvider(),
    DraftsProvider(),
    KnowledgeGraphProvider(),
    KnowledgeGapsProvider(),
    LearningGoalsProvider(),
    RepoSyncsProvider(),
    StatsProvider(),
    TopicsProvider(),
)
